use_frameworks!

platform :ios, '9.0'

target 'JRCustomAliyunPlayersdk_Example' do
  pod 'JRCustomAliyunPlayersdk', :path => '../'

  target 'JRCustomAliyunPlayersdk_Tests' do
    inherit! :search_paths

    
  end
end
